# Generated by Django 3.0.8 on 2020-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='note',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
