# Generated by Django 3.0.8 on 2020-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhold', '0002_data_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='login',
            field=models.CharField(max_length=32, verbose_name='Логин/Email'),
        ),
        migrations.AlterField(
            model_name='data',
            name='note',
            field=models.TextField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
    ]
